### ISSUE TITLE
No heart rate data

### ISSUE THREAD

**Issue by syrm** [04nd01/fitjunction#6]
Heart rate data are not saved

**Comment by 04nd01** [comment]
When creating the Fitbit app, have you chosen the "personal" app type. Some data, like intraday hr will not be available with other types.

If that's not it, do you have any errors related to that in the log file?

**Comment by syrm** [comment]
Yes, no error

**Comment by 04nd01** [comment]
Ok, I got it. Pretty much everything was working fine but the functions responsible for writing the heart rate data to the db just weren't executed.

It's fixed in the [1.1.2](https://github.com/04nd01/fitjunction/releases/tag/1.1.2) release. If you manually edit the "completeness" table and set the time value for the "hr_intraday" back to NULL it will re-do the heart rate data category properly. All the other data should be fine so it's not necessary to start over completely.
